export const data = [
  {
    id: 78,
    title: "Apple MacBook Pro 14 Inch Space Grey",
    price: 1999.99,
    quantity: 2,
    total: 3999.98,
    discountPercentage: 18.52,
    discountedTotal: 3259.18,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/thumbnail.png",
  },
  {
    id: 124,
    title: "iPhone X",
    price: 899.99,
    quantity: 4,
    total: 3599.96,
    discountPercentage: 8.03,
    discountedTotal: 3310.88,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/thumbnail.png",
  },
  {
    id: 125,
    title: "Oppo A57",
    price: 249.99,
    quantity: 5,
    total: 1249.95,
    discountPercentage: 16.54,
    discountedTotal: 1043.21,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/thumbnail.png",
  },
  {
    id: 40,
    title: "Strawberry",
    price: 3.99,
    quantity: 5,
    total: 19.950000000000003,
    discountPercentage: 4.6,
    discountedTotal: 19.03,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Strawberry/thumbnail.png",
  },
  {
    id: 138,
    title: "Baseball Ball",
    price: 8.99,
    quantity: 5,
    total: 44.95,
    discountPercentage: 18.49,
    discountedTotal: 36.64,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/sports-accessories/Baseball%20Ball/thumbnail.png",
  },
  {
    id: 112,
    title: "TV Studio Camera Pedestal",
    price: 499.99,
    quantity: 3,
    total: 1499.97,
    discountPercentage: 15.69,
    discountedTotal: 1264.62,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/TV%20Studio%20Camera%20Pedestal/thumbnail.png",
  },
  {
    id: 111,
    title: "Selfie Stick Monopod",
    price: 12.99,
    quantity: 4,
    total: 51.96,
    discountPercentage: 10.98,
    discountedTotal: 46.25,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Stick%20Monopod/thumbnail.png",
  },
  {
    id: 18,
    title: "Cat Food",
    price: 8.99,
    quantity: 4,
    total: 35.96,
    discountPercentage: 1.15,
    discountedTotal: 35.55,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Cat%20Food/thumbnail.png",
  },
  {
    id: 191,
    title: "Rolex Cellini Moonphase",
    price: 15999.99,
    quantity: 4,
    total: 63999.96,
    discountPercentage: 3.26,
    discountedTotal: 61913.56,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/Rolex%20Cellini%20Moonphase/thumbnail.png",
  },
  {
    id: 94,
    title: "Longines Master Collection",
    price: 1499.99,
    quantity: 3,
    total: 4499.97,
    discountPercentage: 16.44,
    discountedTotal: 3760.17,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-watches/Longines%20Master%20Collection/thumbnail.png",
  },
  {
    id: 32,
    title: "Milk",
    price: 3.49,
    quantity: 3,
    total: 10.47,
    discountPercentage: 9.36,
    discountedTotal: 9.49,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Milk/thumbnail.png",
  },
  {
    id: 181,
    title: "Marni Red & Black Suit",
    price: 179.99,
    quantity: 5,
    total: 899.95,
    discountPercentage: 14.21,
    discountedTotal: 772.07,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-dresses/Marni%20Red%20&%20Black%20Suit/thumbnail.png",
  },
  {
    id: 109,
    title: "Monopod",
    price: 19.99,
    quantity: 3,
    total: 59.97,
    discountPercentage: 12.95,
    discountedTotal: 52.2,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Monopod/thumbnail.png",
  },
  {
    id: 54,
    title: "Citrus Squeezer Yellow",
    price: 8.99,
    quantity: 5,
    total: 44.95,
    discountPercentage: 6.3,
    discountedTotal: 42.12,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/kitchen-accessories/Citrus%20Squeezer%20Yellow/thumbnail.png",
  },
  {
    id: 133,
    title: "Samsung Galaxy S10",
    price: 699.99,
    quantity: 3,
    total: 2099.9700000000003,
    discountPercentage: 1.12,
    discountedTotal: 2076.45,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/thumbnail.png",
  },
  {
    id: 152,
    title: "Tennis Racket",
    price: 49.99,
    quantity: 3,
    total: 149.97,
    discountPercentage: 9.13,
    discountedTotal: 136.28,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/sports-accessories/Tennis%20Racket/thumbnail.png",
  },
  {
    id: 60,
    title: "Grater Black",
    price: 10.99,
    quantity: 3,
    total: 32.97,
    discountPercentage: 16.62,
    discountedTotal: 27.49,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/kitchen-accessories/Grater%20Black/thumbnail.png",
  },
  {
    id: 24,
    title: "Fish Steak",
    price: 14.99,
    quantity: 3,
    total: 44.97,
    discountPercentage: 7.66,
    discountedTotal: 41.53,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/groceries/Fish%20Steak/thumbnail.png",
  },
  {
    id: 153,
    title: "Volleyball",
    price: 11.99,
    quantity: 5,
    total: 59.95,
    discountPercentage: 16.05,
    discountedTotal: 50.33,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/sports-accessories/Volleyball/thumbnail.png",
  },
  {
    id: 193,
    title: "Watch Gold for Women",
    price: 799.99,
    quantity: 3,
    total: 2399.9700000000003,
    discountPercentage: 19.53,
    discountedTotal: 1931.26,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-watches/Watch%20Gold%20for%20Women/thumbnail.png",
  },
  {
    id: 91,
    title: "Sports Sneakers Off White & Red",
    price: 119.99,
    quantity: 2,
    total: 239.98,
    discountPercentage: 1.96,
    discountedTotal: 235.28,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mens-shoes/Sports%20Sneakers%20Off%20White%20&%20Red/thumbnail.png",
  },
  {
    id: 2,
    title: "Eyeshadow Palette with Mirror",
    price: 19.99,
    quantity: 2,
    total: 39.98,
    discountPercentage: 0.7,
    discountedTotal: 39.7,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/beauty/Eyeshadow%20Palette%20with%20Mirror/thumbnail.png",
  },
  {
    id: 172,
    title: "Blue Women's Handbag",
    price: 49.99,
    quantity: 4,
    total: 199.96,
    discountPercentage: 8.08,
    discountedTotal: 183.8,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/womens-bags/Blue%20Women's%20Handbag/thumbnail.png",
  },
  {
    id: 134,
    title: "Vivo S1",
    price: 249.99,
    quantity: 4,
    total: 999.96,
    discountPercentage: 5.64,
    discountedTotal: 943.56,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/thumbnail.png",
  },
  {
    id: 126,
    title: "Oppo F19 Pro+",
    price: 399.99,
    quantity: 1,
    total: 399.99,
    discountPercentage: 14.38,
    discountedTotal: 342.47,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro+/thumbnail.png",
  },
  {
    id: 128,
    title: "Realme C35",
    price: 149.99,
    quantity: 3,
    total: 449.97,
    discountPercentage: 3.97,
    discountedTotal: 432.11,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20C35/thumbnail.png",
  },
  {
    id: 110,
    title: "Selfie Lamp with iPhone",
    price: 14.99,
    quantity: 2,
    total: 29.98,
    discountPercentage: 19.87,
    discountedTotal: 24.02,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Lamp%20with%20iPhone/thumbnail.png",
  },
  {
    id: 141,
    title: "Basketball Rim",
    price: 39.99,
    quantity: 4,
    total: 159.96,
    discountPercentage: 14.7,
    discountedTotal: 136.45,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/sports-accessories/Basketball%20Rim/thumbnail.png",
  },
  {
    id: 107,
    title: "Beats Flex Wireless Earphones",
    price: 49.99,
    quantity: 4,
    total: 199.96,
    discountPercentage: 8.79,
    discountedTotal: 182.38,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Beats%20Flex%20Wireless%20Earphones/thumbnail.png",
  },
  {
    id: 171,
    title: "Pacifica Touring",
    price: 31999.99,
    quantity: 4,
    total: 127999.96,
    discountPercentage: 7.4,
    discountedTotal: 118527.96,
    thumbnail:
      "https://cdn.dummyjson.com/products/images/vehicle/Pacifica%20Touring/thumbnail.png",
  },
];
